[pytest]
testpaths =
    01-namespaces/exercises
    02-module-vs-script/exercises
    03-stdlib-batteries/exercises
    04-imports-and-symbol-tables/exercises
    05-import-mechanism-pythonpath/exercises
    06-compilation-pycache/exercises
    07-packages-and-init/exercises
    08-advanced-import-topics/exercises
    09-dependency-management/exercises
addopts = -v --tb=short --import-mode=importlib

