[pytest]
testpaths =
    01-text-files/exercises
    02-binary-files/exercises
    03-encryption/exercises
    04-streams-and-io/exercises
    05-stream-filtering/exercises
addopts = -v --tb=short --import-mode=importlib

