[pytest]
testpaths =
    01-class-vs-object/exercises
    02-class-definition-and-object-creation/exercises
    03-self-parameter/exercises
    04-instance-vs-class-members/exercises
    05-private-members/exercises
    06-special-methods/exercises
    07-inheritance-basics/exercises
    08-multiple-inheritance/exercises
    09-polymorphism/exercises
    10-large-example-inheritance-polymorphism/exercises
    11-interfaces-in-python/exercises
    12-design-patterns-polymorphism/exercises
addopts = -v --tb=short --import-mode=importlib
