[pytest]
testpaths =
    01-streaming-parser-events/exercises
    02-subclassing/exercises
    03-event-handling/exercises
    04-link-extraction/exercises
    05-tag-counting/exercises
    06-limitations-and-alternatives/exercises
addopts = -v --tb=short --import-mode=importlib

