[pytest]
testpaths =
    01-definition/examples
    01-definition/exercises
    02-arguments/exercises
    03-lambda-calculus/exercises
    04-lambda-usage/exercises
    05-srp/exercises
    06-separation-of-concerns/exercises
addopts = -v --tb=short --import-mode=importlib
