[pytest]
testpaths =
    01-formal-languages/exercises
    02-basic-syntax/exercises
    03-re-module/exercises
    04-groups/exercises
    05-flags/exercises
    06-advanced-patterns/exercises
    07-practical-use/exercises
addopts = -v --tb=short --import-mode=importlib

