[pytest]
testpaths =
    01-exception-vs-error/exercises
    02-try-except-else-finally/exercises
    03-custom-exceptions/exercises
    04-built-in-exceptions/exercises
    05-file-handling-caesar-cipher/exercises
    06-pickle-and-serialization/exercises
addopts = -v --tb=short --import-mode=importlib

