[pytest]
testpaths =
    data-types/examples/tests
    mutability/examples/tests
    control-flow/examples/tests
    running-python/examples/tests
    interpreters/exercises
    running-python/exercises
    data-types/exercises
    mutability/exercises
    control-flow/exercises
addopts = -v --tb=short --import-mode=importlib
